site_name: ymtr.
# site_url: http://doc.ymtr.jp/
docs_dir: 'docs'
copyright: '© yamatora'
use_directory_urls: false # falseでhtmlへのURLになる=htmlで相対リンクが利用できる

# repo_url: https://github.com/yamatora/doc
# repo_name: doc

theme:
  name: material
  palette:
    scheme: slate
    #    # Palette toggle for light mode
    # - scheme: default
    #   toggle:
    #     icon: material/toggle-switch-off-outline
    #     name: Switch to dark mode
    # # Palette toggle for dark mode
    # - scheme: dark 
    #   toggle:
    #     icon: material/toggle-switch
    #     name: Switch to light mode
  # font:
  #   text: Kosugi Maru
  language: ja
  feature:
    tabs: true
  icon:
    logo: material/broadcast
    repo: fontawesome/brands/git-alt
    # favicon: /img/icon.ico
  features:
    - navigation.tabs
    # - navigation.tabs.sticky  # 上付き
    # - navigation.expand       # 常時展開
    # - navigation.prune
    - navigation.top
    # - toc.follow
    # - toc.integrate           # tocを左側に統合
    # - header.autohide

# nav:  # 任意のページ構成
#   - HOME: index.md
#   - Development: /development/
    # - Algorithm: /development/Algorithm/
    # - Tool: /development/Tool/
  # - Note: 
  #   - fastapi: /notes/fastapi/
  #   - nginx: /notes/nginx/

plugins:
#   - tags    # 有効にすると検索BOX消える?
  # - offline # スポンサービルドのみ
  # - offline:
  #     enabled: !ENV [OFFLINE, false]
  - search
  - git-revision-date-localized:  # 最終更新日表示
      # exclude:  # 無視するファイル
      #   - index.md
  - mkdocs-video:
      video_autoplay: True

extra:
  # consent:
  #   title: Cookie
  #   actions:
  #     - accept
  #     - reject
  #     - manage
  #   description: >-
  #     This page is hosted by GitHub pages.
  # font:
  #     text: "Roboto Mono"
  #     code: "Consolas"
  palette:
      primary: "light blue"
      accent: "red"
  social:
    # https://fontawesome.com/  同形式で指定
    - icon: fontawesome/brands/github
      link: https://github.com/yamatora
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/_yamatora
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/_yamatora
    - icon: fontawesome/solid/envelope
      link: https://twitter.com/_yamatora
  generator: false

extra_css:
    - "//fonts.googleapis.com/earlyaccess/notosansjp.css"
    - "//fonts.googleapis.com/css?family=Open+Sans:600,800"
    - "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
    - "css/custom.css"
    - "css/dark.css"

extra_javascript: 
  # - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  # - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
        
markdown_extensions:
  - admonition            # 警告の有効化
  - pymdownx.details      # 
  - pymdownx.superfences
  - pymdownx.arithmatex:  # 数式
      generic: true
  - attr_list             # リンクのボタン化
  - tables                # 明示的な宣言
  - pymdownx.superfences: # mermaidによるダイアグラム
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
  - def_list  # https://dev.classmethod.jp/articles/material-for-mkdocs-lists/
  - pymdownx.tasklist:    # タスクリスト
      custom_checkbox: true 
  - pymdownx.tilde        # 打消し